#!/bin/bash
#set +e
print_usage(){
  echo "Usage: pull-T0-logs <yyyy-mm-dd>"
  echo "Retrieves logs from test directories for specified date"
}
[ $1 ] || { print_usage ; exit ; }
logdate=$1

# create local directories
mkdir AirAccruals-$logdate-T0
cd AirAccruals-$logdate-T0
mkdir 704-accrualeng1 715-accrualeng2

# retrieve logs from air accrual engine v1
scp aklia704.redacted.com:/opt/was/T0_APP02_11/AirAccrualEngine/logs/airaccrualengine.log.$logdate* 704-accrualeng1/

# retrieve logs from air accrual engine v2
scp akl0ia715.redacted.com:/opt/was/T0_APP24_11/AirAccrualEngine/logs/airaccrualengine.log.$logdate* 715-accrualeng2/
